# Interactive graph

## Exploring Trends:  Interactive Visualization of Alcohol-Related Deaths in New York (2003-2020)

In the context of an increasing trend in unnatural fatalities over the years, our analysis has identified a concerning pattern: the growth in the number of alcohol-related deaths stands out as a primary cause. This interactive bar chart meticulously captures the annual toll taken by alcohol-related incidents in New York State from 2003 to 2020. This tool not only serves to present historical data but also invites users to engage with the information, offering a hands-on experience to better understand the dynamics of these changes.

### Instructions

**Add a Bar:** Click on the 'Add bar' button to simulate a projection for the next year.   

**Remove Bar (left):** To remove data from the beginning of the timeline, click the 'Remove bar (left)' button. This will eliminate the earliest year from the visualized data, helping you to focus on more recent years.  

**Remove Bar (right):** To exclude the most recent data point, use the 'Remove bar (right)' button. This function is useful for examining the chart without the influence of the last year's data.

<style>
  * {
    font-family: sans-serif;
  }
</style> 

<div id="plot">
</div>

<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
<script src="scripts/myscript.js"></script>

<button onclick="addBar()">Add bar</button>
<button onclick="removeBarLeft()">Remove bar (left)</button>
<button onclick="removeBarRight()">Remove bar (right)</button>
  
(Tips: If you run out of bars to remove or you want to start the analysis over, simply refresh the page to reset the interactive chart and begin anew.)

